# Generated by Django 4.1.3 on 2023-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=200, null=True)),
                ('PHONE', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productdb',
            name='QUANTITY',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
