# Generated by Django 4.1.3 on 2023-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0005_contactdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
