# Generated by Django 4.1.3 on 2023-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userlogindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('USERNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=100, null=True)),
                ('CONFIRMPASSWORD', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
